### ISSUE TITLE
How to patch the game to play offline?

### ISSUE THREAD

**Issue by meetchal** [ferib/D2R-Offline#10]
I've installed the game successfully, but unsure on how to do the rest. Any help appreciated.

**Comment by ferib** [comment]
Either build the game and invoke the output .exe with args or set debugging arguments in VS and run from VS.
![image](https://user-images.githubusercontent.com/22753171/114815158-f29dc780-9db5-11eb-96f2-e1cff7a06ed1.png)
The 'debug' tab can be found when right-clicking the solution and then clicking on properties.

**Comment by meetchal** [comment]
> 
> 
> Either build the game and invoke the output .exe with args or set debugging arguments in VS and run from VS.
> ![image](https://user-images.githubusercontent.com/22753171/114815158-f29dc780-9db5-11eb-96f2-e1cff7a06ed1.png)
> The 'debug' tab can be found when right-clicking the solution and then clicking on properties.

I just downloaded VS, what do I install with it? I don't really understand anything about this. Sorry I'm not good with this kind of stuff. Not sure how to use it

**Comment by ferib** [comment]
@meetchal may try to download from release? https://github.com/ferib/D2R-Offline/releases/download/v1.0.1/D2ROffline_v1.0.1.zip

Download those files, unzip them in your Diablo II Resurrected folder and then drag the game.exe on top of the D2ROffline.exe

**Comment by Koatohee** [comment]
Guys I have this issue when my character doesn't land the attacks, it's like I'm playing with 500 ms ping or something. Isn't it local? I thought it's not connecting to a server

**Comment by mfrklic** [comment]
> Guys I have this issue when my character doesn't land the attacks, it's like I'm playing with 500 ms ping or something. Isn't it local? I thought it's not connecting to a server

What is your FPS if you type "/fps" in game?

I am running 1080p @ 60fps with vsync turned on and runs fine with max settings on my GTX 1080P TI.

Does it make a difference when you hit "G" to go to classic graphics mode?

The gameplay is all local but maybe something on your system is not liking the new graphics engine. Maybe make sure graphics drivers are up to date and maybe adjust graphics settings?

**Comment by StereopwnZ** [comment]
I drag game.exe to the offline thing it looks like it brings up some sort of window and closes immediately with nothing happening.

**Comment by CDune23** [comment]
> I drag game.exe to the offline thing it looks like it brings up some sort of window and closes immediately with nothing happening.

Try updating your NVIDIA drivers, the one released yesterday. Fixed this issue for me.

**Comment by mfrklic** [comment]
> I drag game.exe to the offline thing it looks like it brings up some sort of window and closes immediately with nothing happening.

Have you tried opening the command prompt to the path where d2roffline.exe is stored and running the following?

D2ROffline.exe “C:\D2R\Game.exe”

Change the path to where you D2R alpha is stored if different.

**Comment by ferib** [comment]
version `v2.0.4-beta` is even more easy to use, just drop the `D2ROffline.exe` and `patches.txt` inside the game folder and double-click the `D2ROffline.exe`, this is explained in the `readme.md` for mode details.
