### ISSUE TITLE
Unziped can't see .exe or .txt files

### ISSUE THREAD

**Issue by SHDWatch** [ferib/D2R-Offline#100]
when I Unzip both D2ROffline.exe and patches.txt files are not there.
Open visual studio no D2ROffline.csproj file, so cant right click and Build .NET Core project
![My folder no exe](https://user-images.githubusercontent.com/82981594/115629774-fd35f080-a2d0-11eb-8a3b-21c556994af3.png)
![vs](https://user-images.githubusercontent.com/82981594/115630185-8f3df900-a2d1-11eb-99c6-8a08129b457c.png)

**Comment by csuhta** [comment]
You downloaded a zip of the project repo itself. The .exe and patches file are here: https://github.com/ferib/D2R-Offline/releases

**Comment by ferib** [comment]
That's because you downloaded the source code...

**Comment by SHDWatch** [comment]
thanks got it
