### ISSUE TITLE
v2.0.8 -FixLocalSave changes all quests to completed status

### ISSUE THREAD

**Issue by esudbrack** [ferib/D2R-Offline#102]

**Comment by ferib** [comment]
Awesome, right ;D?

**Comment by TheOneEyedGrimReaper** [comment]
> Awesome, right ;D?

it's awesome in it's own way, but some people just like me, want to enjoy the game with all of the quests.

**Comment by ferib** [comment]
> > Awesome, right ;D?
> 
> it's awesome in it's own way, but some people just like me, want to enjoy the game with all of the quests.

Oh, well, this patcher was created with the purpose of exploring the game to see how D2R differs from D2 and not for actual gameplay. I am afraid you will have to host a tcp/ip game and play your local character there since the `-FixSaveLocal` auto-completes all quests.

There is a backup file to recover your saved files. Also, feel free to improve the `-FixSaveLocal` and PR it.

**Comment by doyou** [comment]
It's still reported as malicious by MS defender...
BTW:
 0x1446C8:+0x270DC: ~ zhCN
This line works in patches.txt, other localization patches like this may also work well.

**Comment by LazG7** [comment]
Use 2.0.7 if you don't want this to happen.

**Comment by deartonym** [comment]
> > > Awesome, right ;D?
> > 
> > 
> > it's awesome in it's own way, but some people just like me, want to enjoy the game with all of the quests.
> 
> Oh, well, this patcher was created with the purpose of exploring the game to see how D2R differs from D2 and not for actual gameplay. I am afraid you will have to host a tcp/ip game and play your local character there since the `-FixSaveLocal` auto-completes all quests.
> 
> There is a backup file to recover your saved files. Also, feel free to improve the `-FixSaveLocal` and PR it.

Sorry where is the backup file that can recover my saved files? I need to recover my quest as well. thx

**Comment by LazG7** [comment]
> 
> 
> > > > Awesome, right ;D?
> > > 
> > > 
> > > it's awesome in it's own way, but some people just like me, want to enjoy the game with all of the quests.
> > 
> > 
> > Oh, well, this patcher was created with the purpose of exploring the game to see how D2R differs from D2 and not for actual gameplay. I am afraid you will have to host a tcp/ip game and play your local character there since the `-FixSaveLocal` auto-completes all quests.
> > There is a backup file to recover your saved files. Also, feel free to improve the `-FixSaveLocal` and PR it.
> 
> Sorry where is the backup file that can recover my saved files? I need to recover my quest as well. thx

C:\Users\USER_NAME\Saved Games\Diablo II Resurrected Tech Alpha

**Comment by deartonym** [comment]
> > > > > Awesome, right ;D?
> > > > 
> > > > 
> > > > it's awesome in it's own way, but some people just like me, want to enjoy the game with all of the quests.
> > > 
> > > 
> > > Oh, well, this patcher was created with the purpose of exploring the game to see how D2R differs from D2 and not for actual gameplay. I am afraid you will have to host a tcp/ip game and play your local character there since the `-FixSaveLocal` auto-completes all quests.
> > > There is a backup file to recover your saved files. Also, feel free to improve the `-FixSaveLocal` and PR it.
> > 
> > 
> > Sorry where is the backup file that can recover my saved files? I need to recover my quest as well. thx
> 
> C:\Users\USER_NAME\Saved Games\Diablo II Resurrected Tech Alpha

thx for the answer! greetings!

**Comment by doyou** [comment]
> Use 2.0.7 if you don't want this to happen.

2.0.7 is not excepted, I've put it into white list.

**Comment by FunkyMunky1** [comment]
Fixed in https://github.com/ferib/D2R-Offline/pull/124

Added new option:
`-FixLocalSaveNoQuests`

This will complete all three difficulties so you can play single players but will not do any quests or waypoints.

**Comment by ferib** [comment]
This has now been implemented in the release of v2.0.9
