### ISSUE TITLE
Trojan:Win32/Bearfoos.A!ml Detected

### ISSUE THREAD

**Issue by SHDWatch** [ferib/D2R-Offline#103]
Anyone else get this? im new to this can someone please tell me what to do?
![virus](https://user-images.githubusercontent.com/82981594/115635363-89e4ac80-a2d9-11eb-9ba1-014d3c441398.png)

![cant download](https://user-images.githubusercontent.com/82981594/115635823-91588580-a2da-11eb-88dd-737306692dcd.png)

**Comment by ferib** [comment]
You have to whitelist those files in your anti-virus.

**Comment by ferib** [comment]
https://github.com/ferib/D2R-Offline/blob/master/FAQ.md#why-does-it-say-that-this-patch-is-a-virus-or-trojan
