### ISSUE TITLE
from act3 to act5 everything is pitch black

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [ferib/D2R-Offline#104]
**Describe the crash**
everything is pitch black from act3 to act5
i can walk and kill monsters but i don't see anything just the hud and the dropped items names.
i tried at the ferib.dev server, i think this is some copyprotection or something.

**Which version did you use?**
v2.0.8

**Which patches.txt did you use?**
v2.0.8
0xD4AD68:9090
0xD4E25F:909090909090
0xCAFB9D:90B001
0x597E1C:90909090909090
0xC5E81C:9090C346455242: ~ MP stack corruption bypass
0xD615F2:909090909090909090909090909090909090909090909090909090: ~ show all calsses on load (shalzuth)
0x39FC03:9090909090909090909090909090909090909090: ~ allow chars to load (shalzuth)
0x39FCB6:909090909090909090: ~ enable loading into a3-a5 (shalzuth)

**Comment by ferib** [comment]
Easy, press `g`.
AFAIK there are no files for act3 to act5, press `g` while you run around and you may get a few locations to load unfinished textures.

**Comment by TheOneEyedGrimReaper** [comment]
> Easy, press `g`.
> AFAIK there are no files for act3 to act5, press `g` while you run around and you may get a few locations to load unfinished textures.

yeah and all the quests is greyed out because the -FixLocalSave
it says i completed all.
where is the gamesave and the backup locations?

**Comment by ferib** [comment]
> where is the gamesave and the backup locations?

@TheOneEyedGrimReaper, https://github.com/ferib/D2R-Offline/blob/master/FAQ.md#where-are-my-save-files

**Comment by TheOneEyedGrimReaper** [comment]
> > where is the gamesave and the backup locations?
> 
> @TheOneEyedGrimReaper, https://github.com/ferib/D2R-Offline/blob/master/FAQ.md#where-are-my-save-files

thanks again.
i pressed g the original mode is works fine.
in the next release i hope you can fix this game completion problem with the act3-act5 unlocking.
