### ISSUE TITLE
2.0.8 Crashing Act 2

### ISSUE THREAD

**Issue by bvandy123** [ferib/D2R-Offline#105]
Game crashing randomly 2-5 minutes into playing. Deleted everything and did fresh install, same result.

**Comment by ferib** [comment]
Make use of the `-Delay` arg to avoid crashing https://github.com/ferib/D2R-Offline#-delay-delay-in-ms

**Comment by bvandy123** [comment]
Is there a tutorial about how to add delay? Im inexperienced in this area

**Comment by mfrklic** [comment]
Example:
D2ROffline.exe game.exe -Delay 25
