### ISSUE TITLE
Act3 Lights disabled

### ISSUE THREAD

**Issue by RM6SS62** [ferib/D2R-Offline#112]
I can access Act3 but it looks like if level lighting is disabled, I guess this is intentionally made by Blizzard.
Wonder if there is known method to bypass this limitation.

Thanks for all the hard work ferib and other people!

**Comment by csuhta** [comment]
The lights aren’t disabled. There are no graphics or voice files included at all for the later acts in the alpha. You have to play them in legacy mode.
