### ISSUE TITLE
How do I use arguments with D2ROffline.exe like -FixLocalSave

### ISSUE THREAD

**Issue by SHDWatch** [ferib/D2R-Offline#115]
How do I go to Act III, IV, or V?
.\D2ROffline.exe -FixLocalSave were does this go? how do I add it?

**Comment by DEV7163** [comment]
Run it from command prompt

**Comment by SHDWatch** [comment]
C:\Users\***********>.\D2ROffline.exe -FixLocalSave
'.\D2ROffline.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SHDWatch** [comment]
Ok i figured it out sorry for being new lmao thanks for the hint it helped.

**Comment by SHDWatch** [comment]
Well it would seem i can hit play now and choose difficulty but still unable to access A3, says return to main menu.

**Comment by SHDWatch** [comment]
nvm can take wp there
