### ISSUE TITLE
can this method be used for other games?

### ISSUE THREAD

**Issue by comebacktocode** [ferib/D2R-Offline#118]
off topic: I was wondering if this method could be targeted to w3r ptr, for example. (could not find other place to put the question, sorry).

**Comment by ferib** [comment]
The crc32 bypass was forked from one of my Wow related projects: https://ferib.dev/blog.php?l=post/Bypassing_World_of_Warcraft_Crc32_Integrity_Checks

The techniques themselves can be used on other games if they are similar, a good thing Blizzard has this bad habit of copy-pasting existing anti-cheating code from one game to another and calling it a day.

**Comment by comebacktocode** [comment]
yeah, i read this post and found very interesting. unfortunately i do not have enough coding knowledge to be able to do it myself. me and i friend are checking the possibilities to bruteforce into some decr. keys for fenris. or would it be easier to capture the procedure of the key check and by pass it? either way i don't know if for that it is possible to have success.

**Comment by ferib** [comment]
This project is for educational use only, why don't you improve your skills by reading a bit more about it and try again once you have enough skills.
