### ISSUE TITLE
Cannot Run Save Fixer

### ISSUE THREAD

**Issue by NiteKat** [ferib/D2R-Offline#119]
Compiled from master commit ffb921f. On Windows 10. I placed compiled executable in the same folder as Game.exe. In console when I run D2ROffline.exe -FixLocalSave I get the error

[17:51:41.08716]: Error, -FixLocalSave does not exist!
[17:51:41.09399]: Usage: D2ROffline.exe PATH_TO_GAMEDOTEXE
[17:51:41.09399]: Press any key to exit...

If I run D2ROffline.exe E:\D2R\Game.exe -FixLocalSave the executable launches the game with the patches, but does not fix the local save files. Not sure what I'm doing wrong to try to run with this argument.

**Comment by ferib** [comment]
The tool think `-FixLocalSave` is the game path and not `E:\D2R\Game.exe`.

**Comment by NiteKat** [comment]
Yep. No idea why it's thinking that though.

**Comment by mfrklic** [comment]
You might have to pass the first parameter as the game path. I believe "-FixLocalSave" you may only be able to run by itself just to update your saves to unlock waypoints and local play for shared stash access.

Example:
D2ROffline.exe E:\D2R\Game.exe
or
D2ROffline.exe -FixLocalSave
or this may work but I have not tested with latest version to be sure:
D2ROffline E:\D2R\Game.exe -FixLocalSave

**Comment by Urbanhack** [comment]
cuz ure doing it wrong, first copy the offline launcher in d2r folder, then make a offlinelauncher short cut to ur desktop, now add the prefix -FixLocalSave after destination path, like : "c:/d2r/D2ROffline.exe" -FixLocalSave apply and launch. thats all.

**Comment by NiteKat** [comment]
> cuz ure doing it wrong, first copy the offline launcher in d2r folder, then make a offlinelauncher short cut to ur desktop, now add the prefix -FixLocalSave after destination path, like : "c:/d2r/D2ROffline.exe" -FixLocalSave apply and launch. thats all.

That is definitely a work around, but shouldn't I be able to pass parameters via the command prompt, or am I misremembering?

**Comment by ericschn** [comment]
The -FixLocalSave argument can only work when there is no other arguments, and none are needed as it only converts your saves as a one-off process and does not need the Game.exe location. 

If running D2ROffline.exe with -FixLocalSave, powershell example:
`.\D2ROffline.exe -FixLocalSave`
gives you the error:
`[17:51:41.08716]: Error, -FixLocalSave does not exist!`
either you have a typo in the argument, or are using a version before the -FixLocalSave argument existed.

**Comment by NiteKat** [comment]
As stated in the issue opening comment, I built from ffb921f which has the code for the argument in it. I am using Command Prompt though and now PowerShell, so I wonder if there's just something about Command Prompt and passing arguments that I am missing.

**Comment by ericschn** [comment]
Both `D2ROffline.exe -FixLocalSave` and `.\D2ROffline.exe -FixLocalSave` work for me using Windows command prompt.

If you're still having the issue, try sharing a screenshot of your command prompt output like this:
![cmdD2rR1](https://user-images.githubusercontent.com/18365781/116012536-a42bcc80-a5f0-11eb-9d35-132b0297aad6.PNG)

**Comment by ferib** [comment]
Please try v2.0.9, the arg handling has been improved in #128
