### ISSUE TITLE
Patch always fails

### ISSUE THREAD

**Issue by erfg12** [ferib/D2R-Offline#12]
```[09:11:07.58805]: Launching game...
[09:11:07.60489]: Process started...
[09:11:08.70969]: Suspending process...
Unhandled exception. System.ComponentModel.Win32Exception (299): Only part of a ReadProcessMemory or WriteProcessMemory request was completed.
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at D2ROffline.Program.Main(String[] args) in C:\Users\newgm\git\D2R-Offline\Program.cs:line 56
```
![](https://i.postimg.cc/CwXpnDbX/Capture.png)

**Comment by ferib** [comment]
Whats the state of the game process when this happens? is it gone? crashed? exited? still somewhere idle?

**Comment by erfg12** [comment]
I never see the game launch, event viewer shows Game.exe never crashed. I'm guessing the process opens then immediately closes.

**Comment by ferib** [comment]
one way or another, the tool is not able to access the process. try to disable anti-virus _(in case you trust our code)_ launch VS as admin and change the `Thread.Sleep(1100)` at line `43`, increase the number to extend the delay before it patches. using to big of a delay and the patch may fails (but game should start up)

**Comment by AvidExplorer** [comment]
If I open the game by double clicking Game.exe, a crash file is created at `C:\Users\User\AppData\Local\Temp\BlizzardError\yyyy-dd-mm`

The main content is this:
```

<Exception.Summary:>
ACCESS_VIOLATION

<:Exception.Summary>

<Exception.Assertion:>

Thread 0x000007fc "Main Thread" [Stack Base: 0x000000B955D00000 Used Space: 45344/1048576 bytes]
DBG-ADDR<00007FF77BAFE596>("Game.exe")
DBG-ADDR<00007FF77BAF371E>("Game.exe")
DBG-ADDR<00007FF77B631477>("Game.exe")
DBG-ADDR<00007FF77B217E04>("Game.exe")
DBG-ADDR<00007FF77B0E46ED>("Game.exe")
DBG-ADDR<00007FF77B0E5AE3>("Game.exe")
DBG-ADDR<00007FF77B0E5D83>("Game.exe")
DBG-ADDR<00007FF77BBFEE12>("Game.exe")
DBG-ADDR<00007FFF8BD07034>("KERNEL32.DLL")
DBG-ADDR<00007FFF8C862651>("ntdll.dll")
```

If I open the game through a compiled D2ROffline.exe with 320 ms for the Thread Sleep, I also get the same error:

```
<Exception.Summary:>
ACCESS_VIOLATION

<:Exception.Summary>

<Exception.Assertion:>

Thread 0x00001be4 "Main Thread" [Stack Base: 0x000000F5AAB60000 Used Space: 45024/1048576 bytes]
DBG-ADDR<00007FF77BAFE596>("Game.exe")
DBG-ADDR<00007FF77BAF371E>("Game.exe")
DBG-ADDR<00007FF77B631477>("Game.exe")
DBG-ADDR<00007FF77B217E04>("Game.exe")
DBG-ADDR<00007FF77B0E46ED>("Game.exe")
DBG-ADDR<00007FF77B0E5AE3>("Game.exe")
DBG-ADDR<00007FF77B0E5D83>("Game.exe")
DBG-ADDR<00007FF77BBFEE12>("Game.exe")
DBG-ADDR<00007FFF8BD07034>("KERNEL32.DLL")
DBG-ADDR<00007FFF8C862651>("ntdll.dll")
```

Perhaps those who have downloaded the game through https://github.com/barncastle/Battle.Net-Installer/releases/tag/v1.3 have a different Game or missing files than those who got the game trough the official bnet launcher?

My Game.exe MD5 is:
Algorithm : MD5
Hash      : 826588779961B38151B206675636BB02
Path      : Game.exe

**Comment by erfg12** [comment]
Disabled Windows UAC, Defender and Firewall (no 3rd party tools installed).
I got the game files from the tool provided in the readme. The MD5 is `826588779961b38151b206675636bb02`

**Comment by ferib** [comment]
@erfg12 this may be a duplicate of https://github.com/ferib/D2R-Offline/issues/2
Can you provide more details on the exception?

**Comment by erfg12** [comment]
I tried the pre-compiled release and compiling myself. Same outcome. Not sure what more information is needed. Let me know, thanks.

**Comment by erfg12** [comment]
After using the latest bnetinstaller command, and updating the code to the latest, the game now launches fine.
