### ISSUE TITLE
D2ROffline.dll in Release Build v.1.0.1 flagged by Microsoft Defender

### ISSUE THREAD

**Issue by juraisa** [ferib/D2R-Offline#13]
D2ROffline.dll in Release build v1.0.1 is flagged as a virus by Windows Defender. Compiling directly from source does not cause this check to trigger using current master branch. Is something going on with how you are compiling the release build?

Compiling from source in VS2019 doesn't seem to cause the DLL to flag for the 'runtime-modules' tag that Virus Total is detected, nor the Microsoft detected trojan/malware or Qihoo-360, which the DLL in the release file does.

Microsoft Defender Antivirus has detected malware or other potentially unwanted software.
 For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Wacatac.B!ml&threatid=2147735505&enterprise=0
 	Name: Trojan:Win32/Wacatac.B!ml
 	ID: 2147735505
 	Severity: Severe
 	Category: Trojan
 	Path: file:_C:\Battle.net\Diablo II Resurrected\D2ROffline.dll
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: Real-Time Protection
 	User: <Redacted>
 	Process Name: C:\Windows\explorer.exe
 	Security intelligence Version: AV: 1.335.889.0, AS: 1.335.889.0, NIS: 1.335.889.0
 	Engine Version: AM: 1.1.18000.5, NIS: 1.1.18000.5

Virustotal:

e48c4765e11ef6ec56efa1e01bfd29c3d0da87e2c24bdf839224c0af859b66d4
D2ROffline.dll
assembly peexe runtime-modules

Avast

Win32:MalwareX-gen [Trj]
AVG

Win32:MalwareX-gen [Trj]
Avira (no cloud)

TR/Dropper.Gen
Cybereason

Malicious.1d5e2b
Cylance

Unsafe
Cynet

Malicious (score: 99)
eGambit

Unsafe.AI_Score_98%
Kaspersky

HEUR:Trojan.Win32.Generic
Microsoft

Trojan:Win32/Wacatac.B!ml
Qihoo-360

Win32/TrojanDropper.Generic.HgIASSwA
Rising

Dropper.Generic!8.35E (TFE:dGZlOg1erXyjW3+yEQ)
SentinelOne (Static ML)

Static AI - Malicious PE
ZoneAlarm by Check Point

HEUR:Trojan.Win32.Generic

**Comment by ferib** [comment]
I am aware that your virus scanner may not like this at all.
The OS provides us, developers, with functions such as OpenHandle, ReadProcessMemory, WriteProcessMemory that we can use to manipulate the memory of another process.
The functions are well known to be used by Malware, most of the time they are used to manipulate a legitimate process to execute malicious tasks to either escalate privileges or to reduce detection.

Please note that we are also manipulating an existing, legitimate process, to manipulate its execution, of course, this is not for malicious purposes. Most anti-virus software flags the executable for using those memory functions due to their common use in malware.

So with that being said, don't bother using the release `.exe` file, instead, go build your own while you read over the source code to verify there is nothing malicious inside the source code ;D

**Comment by juraisa** [comment]
I mean, my main question is, why does the compiled DLL from the Release tag flag in defender when compiled on my box with VS2019 it does not?

Windows Defender is a pretty hard one to brush off as 'well your antivirus might not like it', are you doing anything custom when you are building the release tag? Are you using a specific version of VS/dotnet that is causing it ot get flagged? Thats a pretty dismissive answer above.

**Comment by ferib** [comment]
@juraisa I did build using Release settings, meaning code optimization was enabled.
I think this something windows specific, your windows user builds those files, hence why the windows defender may not even bother looking into them or loosens the definition on those files?

**Comment by BullHorn7** [comment]
Windows Defender is not the only one complaining

![](https://i.imgur.com/uGVEaSt.png)

**Comment by arthurEspooner** [comment]
ESET shows everything clean when grabbed via git clone and compiled.

**Comment by ferib** [comment]
https://www.virustotal.com/gui/file/827dc558124ebd82b40097a5a21a258ff7ec92003a5058ffea5d744927294049/detection
https://www.virustotal.com/gui/file-analysis/ZDJkMGEyNDkxYjhjNTFmMGUwOGNiMGY1Mzg4M2Q4NTM6MTYxODUyOTg2Ng==/detection
https://www.virustotal.com/gui/file-analysis/NTA0OWRjNzhhMjk0OGUxZjljNTViM2MyNDczZTRiZjg6MTYxODUyOTkxMw==/detection

I have uploaded multiple builds where I stripped out a few things to see how it differs, seems like they all get 10+ triggers on VirusTotal?

**Comment by tildebyte** [comment]
Did you not notice the 46 engines detecting nothing?

That's ~75% "OK", ~25% "Not OK"

How interesting that the 25% includes Kaspersky, McAfee, Symantec, Microsoft... Big Anti-Virus.

If you think that they *don't* have actual agreements in place with software vendors, including game developers/publishers, to flag *completely safe* hacks/cracks/keygens, not as "undesirable", but as *actually harmful*... well, you are very naive.

Obviously I'm not saying that *all* hacks/cracks/keygens are perfectly safe, nor that you should *always* favor the majority in a 75/25 split vote, but in **this specific** case...

**Comment by arthurEspooner** [comment]
yep, those results are fake news and anyone who uses those AV anyway is a silly goose. ty for your work @ferib !

**Comment by ferib** [comment]
I think we all can agree that you can ignore the warning and take the risk or just build them yourself while you verify the source code.
