### ISSUE TITLE
Virus detected message

### ISSUE THREAD

**Issue by ToporPesteCap** [ferib/D2R-Offline#132]
Hello there, can someone help me with this problem? It shows me that the zip file is a trojan virus and windows defender it deletes automacily. Do you know why windows defender recognize that zip fille as a trojan?
![iossue](https://user-images.githubusercontent.com/83547780/116821216-a4dcd980-ab81-11eb-8dc7-d9fa942e4bd5.png)

**Comment by ferib** [comment]
Related to #33
