### ISSUE TITLE
-txt does not work

### ISSUE THREAD

**Issue by Crazyloon** [ferib/D2R-Offline#20]
I extracted the runes.txt from the CASC and edited it to allow all of the ladder-only runewords.

I placed the updated runes.txt in several directories (I wasn't sure which one it had to be in).

.../D2R/Data/global/excel/
.../D2R/Data/data/global/excel
.../Saved Games/Diablo II Resurrected Tech Alpha/data/global/excel

I then run D2R-Offline with the command:
dotnet run --project .\D2ROffline.csproj D:\Games\D2R\Game.exe -txt

I also tried: 
dotnet run --project .\D2ROffline.csproj D:\Games\D2R\Game.exe -direct -txt

I also tried rebuilding the executable and running it with both of these options (built with one option at a time, not both):
pInfo.Arguments = "-direct -txt"
pInfo.Arguments = "-txt"

After each test I attempted to build a Spirit. In addition, I tried to set Smoke to be a ladder-only runeword and built it as well. Smoke always completed as normal, Spirit would not.

Are you sure -txt works with modified text files, or am I not doing it correctly?

**Comment by ferib** [comment]
The patcher is forwarding arguments to the game.exe, but the game.exe needs to be patched to get it functioning.
I have seen people handing out patches like these but none of them are my work.

Anyways, if you happened to have such a patch, just place then in your `patches.txt` file and it should work!

**Comment by Crazyloon** [comment]
Ok, thanks. This is working as intended then - I'm just missing the requisite patch.
