### ISSUE TITLE
How do you work TCP/IP Multiplayer?

### ISSUE THREAD

**Issue by Diablo91020** [ferib/D2R-Offline#21]
I have the game installed and everything set up for local play, and i can host TCP/IP Games, but once my friend tries to join, he cant. We pinged each other on Hamachi so there is a established connection through Hamachi.
Is there an specific software that works for it or a workaround that someone has found?

**Comment by mfrklic** [comment]
My brother and step dad were able to play on local lan via TCP/IP and I was able to play with my brother over the internet with hamachi. Maybe you have windows firewall or something blocking connection?

**Comment by Diablo91020** [comment]
I will try turning off the firewall and see if it works.

**Comment by mfrklic** [comment]
Make sure to load himachi first and start it up then load the game. For us it showed the himachi IP address and we used that.  Make sure the second person joins the host IP of course.

**Comment by ferib** [comment]
These questions are related to the game itself, and not to the patching or tool itself.
Oh and one thing to keep in mind is that joining a server multiple times may not work, just restart the game every time you need to join a new tcp/ip game.

**Comment by CDune23** [comment]
Krydar compiled this save fixer, just import your saves one by one with D2 closed and single player will work, no need to mess with TCP/IP anymore. Much easier.

https://github.com/Krydar/D2RSaveFix/releases/tag/v1.0.0

**Comment by Diablo91020** [comment]
Thanks, I got it to work @mfrklic
