### ISSUE TITLE
Language Change

### ISSUE THREAD

**Issue by 4eveRS** [ferib/D2R-Offline#24]
Hello,

I noticed that there was an update to the readme, informing how to perform a language change.

I followed it, but nothing changed in the game.

Do I need to download the language pack or something like that?

Anyway, thanks for the incredible work!

**Comment by ferib** [comment]
This language is very tricky.
I have been working all day in the hopes to get it to work, but there is a very limited timeframe available to patch the game.
The language must be patched before the game window is created but after an unknown scan is done, this unknown scan will trigger a crash X minutes in-game, giving me a very hard time debugging. So far, there is something working but not stable enough to release.

**Comment by 4eveRS** [comment]
Ah, understood.

I'm sure you will able to crack it soon 😉.
