### ISSUE TITLE
IP Multiplayer access

### ISSUE THREAD

**Issue by glockemonster** [ferib/D2R-Offline#29]
I'm trying to join my friend via IP but it is stuck at Please Wait.... forever. Also when installing the zip file, there's no SLN file anymore?

**Comment by mfrklic** [comment]
Are you guys in the same network locally? TCP/IP is local LAN only and I have tested it works.

If you want to play over internet with friend you need something like Hamachi to create a virtual local network (free):
https://www.vpn.net/

**Comment by glockemonster** [comment]
@mfrklic we are playing in the same room, but have different host IP's. We can also use Radmin VPN but that hasn't worked

**Comment by mfrklic** [comment]
If your on the same network yes each of you has a different local host IP. Just choose which person will be the host and have the other person join that host's IP. Also the host may need to make sure to disable any firewall like windows/microsoft firewall.

**Comment by ferib** [comment]
I noticed that the game sometimes bugs out on connecting, you may get stuck in "Please Wait...", just cancel and connect again.
After a few failed attempts, just exit the game and restart again, if it keeps failing then the issues may be at the host.
