### ISSUE TITLE
Are there any patches to unlock Acts 3-5?

### ISSUE THREAD

**Issue by Hondelyk** [ferib/D2R-Offline#30]
As per title. Is there a way to unlock Acts 3, 4 and 5, or simply game data does not include those, so it is impossible?

**Comment by zagorim** [comment]
it's possible but the game doesn't include remastered data so you are forced to play with old graphics or almost all the models, textures and other art will be invisible

**Comment by Crazyloon** [comment]
There is a pull request open for adding this, in the meantime, you can download and run this https://github.com/nt153133/D2RSaveFix

Or modify your code locally to include what is in the pull request here.

Remember to always back up your saved characters before messing with them.

**Comment by Hondelyk** [comment]
> 
> 
> it's possible but the game doesn't include remastered data so you are forced to play with old graphics or almost all the models, textures and other art will be invisible

Thanks for the info, do you know however if finishing game on normal difficulty "the old way" allows access to cows? I have edited my save to "complete" normal difficulty so i can load saves, but i can't do the cows and also when starting game in nightmare it seems like it is somehow bugged. Monsters are giving little to none experience and akara is only selling minor potions which.

**Comment by Crazyloon** [comment]
I have access to cows, however, I initially created my character in Hero Editor and unchecked that box.

**Comment by Hondelyk** [comment]
> 
> 
> There is a pull request open for adding this, in the meantime, you can download and run this https://github.com/nt153133/D2RSaveFix
> 
> Or modify your code locally to include what is in the pull request here.
> 
> Remember to always back up your saved characters before messing with them.

Hi Crazyloon,

I have used this savefix and I can select nightmare difficulty when loading game, however I do not have access to ACT's 3-5 on normal mode (Meshiff does not want to take me to Act 3) nor can i go to cows and playing on Nightmare seems bugged as Akara is only selling minor potions like on normal

**Comment by Crazyloon** [comment]
I can't help you with Meshif. I created all of my characters with Hero Editor after spending hours trying to figure out which offsets to change for Meshif quest =\

**Comment by Hondelyk** [comment]
> 
> 
> I can't help you with Meshif. I created all of my characters with Hero Editor after spending hours trying to figure out which offsets to change for Meshif quest =\

When i create a character in hero editor and i try to use it in D2 Resurrected im getting "Unable to enter game, Bad character quest data"

**Comment by mfrklic** [comment]
@Crazyloon Do you happen to know which offset was changed?

Would be nice at the very least if someone knew how to unlock the ACT 3 town waypoint in saves then we could just manually jump to ACT 3 when done if we want to progress in classic mode.

**Comment by nuckable** [comment]
With Hero Editor you can give yourself all waypoints, quests and introductions (not sure if you need the introductions but it doesn't hurt).
In order to edit characters from D2R you'll wanna go to Options and set "Error Reporting and Response" to the 2nd option and "Disable Version Warning Messages" to "Do NOT Show Version Warning Messages".
(If you don't have the original D2 installed you may wanna disable "Search for D2 Directory" by selection "Only the first time Hero Editor is started")
I would advise against doing this with characters you've already levelled with or wanna keep the equipment of (or use a backup).
But once you've given yourself all the things I mentioned initially you can go to the acts past the first 2 and everything but the torches and some characters will be black
![image](https://user-images.githubusercontent.com/11585191/115118629-6998b300-9fa4-11eb-99d6-088abf83ff8f.png)

It works if you switch to the legacy graphics mode though
![image](https://user-images.githubusercontent.com/11585191/115118640-761d0b80-9fa4-11eb-8736-7e0fa870cf6b.png)

**Comment by Hondelyk** [comment]
Closing issue, as Hero Editor solution seems to work fine. My advise is to create a new character, close D2R, edit that newly created character via Hero Editor (change Hero Editor settings as per @nuckable comment above) and you are good to go.

**Comment by comebacktocode** [comment]
> With Hero Editor you can give yourself all waypoints, quests and introductions (not sure if you need the introductions but it doesn't hurt).
> In order to edit characters from D2R you'll wanna go to Options and set (...)

Which editor did you use, please?
I tried several times with the old Hero Editor 1.4 used for d2, fixsave in d2r but it never loads the game. "game is full" or "bad quest data" message appears.

thanks

**Comment by Hondelyk** [comment]
> 
> 
> > With Hero Editor you can give yourself all waypoints, quests and introductions (not sure if you need the introductions but it doesn't hurt).
> > In order to edit characters from D2R you'll wanna go to Options and set (...)
> 
> hey @nuckable, which editor did you use, please?
> I tried several times with the old Hero Editor 1.4 used for d2, fixsave in d2r but it never loads the game. "game is full" or "bad quest data" message appears.
> 
> thanks

I was using HeroEditor 1.04 and i had problems when editing saves that had some progress made on them via game, but if I just created character in the game, instantly exited the game and edited this saved file via HeroEditor everything was working for me.

**Comment by comebacktocode** [comment]
i keep getting "game is full" message. i am using "zonfire99 edition" for hero editor 1.04. 

-i created a new player, saved and exit d2r using 2.0.7.
-i gave all waypoints for all modes. 
-for quests i set all to "just finished" in all acts and modes. 
-i gave all introductions and all welcomed backs. 
-i set the player to start in act 3, kurast docks.

any clues, please?

**Comment by Hondelyk** [comment]
> 
> 
> i keep getting "game is full" message. i am using "zonfire99 edition" for hero editor 1.04.
> 
> -i created a new player, saved and exit d2r using 2.0.7.
> -i gave all waypoints for all modes.
> -for quests i set all to "just finished" in all acts and modes.
> -i gave all introductions and all welcomed backs.
> -i set the player to start in act 3, kurast docks.
> 
> any clues, please?

Could you try to leave the starting location as Act 1 or Act 2 and check if this will let you in to the game? I think the issue may be related to starting location. When you are loaded into the game you should be able to use Waypoint to go to Acts 3, 4 or 5, but leaving the game while being in one of those acts may cause those "bad quest data" issues.

**Comment by comebacktocode** [comment]
> Could you try to leave the starting location as Act 1 or Act 2 and check if this will let you in to the game? I think the issue may be related to starting location. When you are loaded into the game you should be able to use Waypoint to go to Acts 3, 4 or 5, but leaving the game while being in one of those acts may cause those "bad quest data" issues.

did not work as well. now it is showing "game is full" again. maybe if you have a char that works for you and you attach here, so i can test? i cannot understand what I may be doing wrong. i can as well post my char. 
[sk-balrog.zip](https://github.com/ferib/D2R-Offline/files/6351874/sk-balrog.zip)

**Comment by Hondelyk** [comment]
> 
> 
> > Could you try to leave the starting location as Act 1 or Act 2 and check if this will let you in to the game? I think the issue may be related to starting location. When you are loaded into the game you should be able to use Waypoint to go to Acts 3, 4 or 5, but leaving the game while being in one of those acts may cause those "bad quest data" issues.
> 
> did not work as well. now it is showing "game is full" again. maybe if you have a char that works for you and you attach here, so i can test? i cannot understand what I may be doing wrong. i can as well post my char.
> [sk-balrog.zip](https://github.com/ferib/D2R-Offline/files/6351874/sk-balrog.zip)

Hey, I have changed all the quests from just finished to long finished and it seems to be working fine now.
[sk-balrog.zip](https://github.com/ferib/D2R-Offline/files/6351992/sk-balrog.zip)

**Comment by nuckable** [comment]
I used Hero Editor 1.04 but had to enable the options I specified in my post. I forgot to mention though, that after editing the character I still had to use the D2RSaveFix.exe (which can now be done via the -FixLocalSave argument. As mentioned by Hondelyk, you don't want to do this with existing characters.
So here's what you wanna do:
1. Create a character in the game
2. Exit game
3. Open up Hero Editor 1.04 and make the adjustments to the Options as stated in my post
4. Load your character and give it waypoints & quests as you'd like
5. Save and close
6. Start D2ROffline with the -FixLocalSave argument or run the D2RSaveFix
7. Run the game normally

If you starting act is past the 2nd the background in the main menu will be rendered as black but you should be able to load in just fine. If you want to actually play you'll probably wanna switch to Legacy graphics (the default key for that is G)
