### ISSUE TITLE
Prevent Map Regeneration?

### ISSUE THREAD

**Issue by Gaudon** [ferib/D2R-Offline#32]
As single player doesn't load I have to host tcp/ip games which always forces a map regeneration. 

Is there a way to mimic single player and prevent this regeneration from happening?

**Comment by ferib** [comment]
Single-player will be fixed in #22

**Comment by mfrklic** [comment]
> As single player doesn't load I have to host tcp/ip games which always forces a map regeneration.
> 
> Is there a way to mimic single player and prevent this regeneration from happening?

@Gaudon Until that fix is put into the next release you can use the following tool to allow single player for your save again:
https://github.com/Krydar/D2RSaveFix/releases

**Comment by Gaudon** [comment]
@ferib @mfrklic I just cloned the PR and built the project myself and tested it. It does indeed allow me back into single player.

**Comment by Gaudon** [comment]
I will say it's not all perfect though.. I now have multiple maps all layered on top of one another in both legacy and alpha view. Not sure if this is a bug in the save file patcher, the pre corrupted state, the alpha itself, or what though!

**Comment by mfrklic** [comment]
Weird. I have not experienced this issue. Maybe try opening as TCP/IP for one more map regeneration saving and going back to single player to see if it locks down to single static map?

**Comment by Gaudon** [comment]
> 
> 
> Weird. I have not experienced this issue. Maybe try opening as TCP/IP for one more map regeneration saving and going back to single player to see if it locks down to single static map?

No dice. Even if I load TCP/IP with hosting a new game, some areas already have an incorrect map pre-populated.

![image](https://user-images.githubusercontent.com/1593839/115120461-3ba57580-9f88-11eb-82fb-c9e6bfaad0d1.png)

For example, just loaded in here for the first time, most of these boundaries don't actually exist.

**Comment by Gaudon** [comment]
This was actually pretty easy to fix. I deleted all the <character_name>.map files from my save directory and it seems to be resolved.
