### ISSUE TITLE
Anti-Virus auto deletion

### ISSUE THREAD

**Issue by ferib** [ferib/D2R-Offline#33]
Hello, it seems that anti-virus does not like my work at all.
Since a couple of minutes ago, I decided to build my code and noticed that VS prompts with the following error:
![image](https://user-images.githubusercontent.com/22753171/115118600-40782280-9fa4-11eb-9995-9035d5211151.png)

So I look at my `bin/Release` folder, tried to execute the binary there, and got this error:
![image](https://user-images.githubusercontent.com/22753171/115118613-55ed4c80-9fa4-11eb-86b9-7ee3021677e8.png)

Unfortunately, the only way to prevent this auto-detection is to either completely *disable* your Anti Virus, or whitelist each and every build. I do not recommend disabling your antivirus at all but seems like this is the only way.

**Comment by mfrklic** [comment]
Yikes - No issues here for me yet. What anti-virus tool is doing that for you? Windows Defender?

Interesting that it was not doing this before but now it is :/ Like as if someone submitted it and it got flagged to block or really doesn't like some new change.

**Comment by hjlinde** [comment]
I also started to see that when building it with VSCode. Weirdly shalzuth's tool does not get flagged, even if you download the exe from github. There's gotta be something in the code that is triggering this. @ferib is any of the code copied from somewhere aside from your crc stuff?

**Comment by ferib** [comment]
> What anti-virus tool is doing that for you? Windows Defender?

@mfrklic Windows Defender indeed.

> I also started to see that when building it with VSCode. Weirdly shalzuth's tool does not get flagged, even if you download the exe from github.

@hjlinde His project seems less popular and he code signs his executables, which adds more 'trust' to them.

It's just weird that they started triggering today.. it's like the project became popular and that *some* is trying to detect the tool and flag for malware to prevent spreading.

According to my Windows Defender, it's flagged as "Bhavior:Win32/DefenseEvasion.KQ!ml".
I am aware that my memory manipulation methods used are common in malware, but still.

Maybe I should code sign my own executables?

**Comment by hjlinde** [comment]
> According to my Windows Defender, it's flagged as "Bhavior:Win32/DefenseEvasion.KQ!ml".

Its just bizzare how it keeps detecting as differing things lol. For me it shows as Trojan:Win32/Wacatac.B!ml and also Backdoor:Win32/Bladabindi!ml

> Maybe I should code sign my own executables?
That's never a bad idea :)

**Comment by ferib** [comment]
> That's never a bad idea :)

Any recommendations? also, I did made some money from people sponsoring me and I'm not afraid to put it all into this project.

**Comment by keton** [comment]
If I can throw in my 2 cents start code signing. Then you'll got option for a prompt from smartScreen 'this is software from unknown source are you sure?' As more people use soft signed by you the cert will get trusted an the prompt will go away.

**Comment by hjlinde** [comment]
> > That's never a bad idea :)
> 
> Any recommendations? also, I did made some money from people sponsoring me and I'm not afraid to put it all into this project.

I've never done code-signing on Windows Dev side I'm afraid. Only time I do that is with Xcode/macOS stuff.

**Comment by ferib** [comment]
> If I can throw in my 2 cents start code signing. Then you'll got option for a prompt from smartScreen 'this is software from unknown source are you sure?' As more people use soft signed by you the cert will get trusted an the prompt will go away.

Can you toss me a website where I can buy a decent cert? when I google for one I get a ton of ad's in the search results, not knowing which one to pick.

**Comment by keton** [comment]
@ferib MS has a list: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by hjlinde** [comment]
https://www.comodoca.com/codesigning
One of the cheaper ones from what I could find.

**Comment by ferib** [comment]
> https://www.comodoca.com/codesigning
> One of the cheaper ones from what I could find.

Yeah.. on checkout they show the 21% taxes :/
That's still a total of 216.59$

**Comment by hjlinde** [comment]
> > https://www.comodoca.com/codesigning
> > One of the cheaper ones from what I could find.
> 
> Yeah.. on checkout they show the 21% taxes :/
> That's still a total of 216.59$

See my edited comment above.

**Comment by ferib** [comment]
its just a little weird it has SSL in the name and then "Total Domains: 1" on the bottom, you sure this is code signing? it has another one payment form on the bottom of the page.

<img width="707" alt="Screen Shot 2021-04-17 at 7 01 55 PM" src="https://user-images.githubusercontent.com/22753171/115120766-72db4d00-9faf-11eb-93db-91da5058075c.png">

**Comment by hjlinde** [comment]
I mean if you add to cart it shows it's a code signing cert. So I would hope it is!
![image](https://user-images.githubusercontent.com/920794/115120961-8cc95f80-9fb0-11eb-8a1b-c94e34189d76.png)

Whether this will ultimately stop it from being flagged I'm honestly not sure? I don't know enough to say for certain it will.

**Comment by jobes911** [comment]
its say to drag the D2ROffline.exe and patches.txt to your Diablo 2 Resurrected game folder   but theres not  D2ROffline.exe, only D2ROffline.csproj or csprojuser

**Comment by ferib** [comment]
> its say to drag the D2ROffline.exe and patches.txt to your Diablo 2 Resurrected game folder but theres not D2ROffline.exe, only D2ROffline.csproj or csprojuser

Maybe Anti-Virus deleted it hehe

**Comment by hjlinde** [comment]
> > its say to drag the D2ROffline.exe and patches.txt to your Diablo 2 Resurrected game folder but theres not D2ROffline.exe, only D2ROffline.csproj or csprojuser
> 
> Maybe Anti-Virus deleted it hehe

Or downloaded the source files instead of the binary...

**Comment by ferib** [comment]
> I mean if you add to cart it shows it's a code signing cert. So I would hope it is!

I just didn't feel like buying something and refunding it to buy the one recommended by the Microsoft page, so I just got the more expansive one. the cert is pending verification, lets hope those people work on weekends so I can get a signed build up tonight!

**Comment by DravenTheWicked** [comment]
Even the .rar files are showing up as being flagged now too.

Seems theyre on to something?

**Comment by ferib** [comment]
> Even the .rar files are showing up as being flagged now too.
> 
> Seems theyre on to something?

Yeah it's problematic, check this out: https://www.youtube.com/watch?v=-iJajUcI8k0
The ASCII triggers the flagging? it's weird!

**Comment by mfrklic** [comment]
> > Even the .rar files are showing up as being flagged now too.
> > Seems theyre on to something?
> 
> Yeah it's problematic, check this out: https://www.youtube.com/watch?v=-iJajUcI8k0
> The ASCII triggers the flagging? it's weird!

That's kind of hilarious! Still probably good to get signed but nice find on that quick fix!

**Comment by DravenTheWicked** [comment]
Its now saying the 2.0.4 version is either unknown format or damaged. wonder whats up with that?

**Comment by DravenTheWicked** [comment]
> 
> 
> Its now saying the 2.0.4 version zip is either unknown format or damaged. wonder whats up with that?

i am using winrar btw.

**Comment by Fidelity88** [comment]
I had the same issue, fixed it by (temporarily) disabling Windows Real-time protection

![afbeelding](https://user-images.githubusercontent.com/2750761/115125244-14ba6400-9fc7-11eb-9919-6c2a66296a4f.png)

**Comment by mfrklic** [comment]
Yes looks like Chrome has blocked it as well now:

![image](https://user-images.githubusercontent.com/1459841/115125243-a00e0800-9f7b-11eb-8587-b5920fb64361.png)

@ferib I know you are working on getting it signed but maybe do a new release build in the mean time to possibly avoid the ascii false positive?

**Comment by DravenTheWicked** [comment]
What i did was just make an exception to folder containing the original files and its working.

**Comment by ferib** [comment]
> @ferib I know you are working on getting it signed but maybe do a new release build in the mean time to possibly avoid the ascii false positive?

Believe it or not but a couple of hours after changing the ASCII it got flagged again and was auto removed while trying to build it... I wish I could avoid this problem ASAP because there are so many noobs having trouble with that.

**Comment by mfrklic** [comment]
> > @ferib I know you are working on getting it signed but maybe do a new release build in the mean time to possibly avoid the ascii false positive?
> 
> Believe it or not but a couple of hours after changing the ASCII it got flagged again and was auto removed while trying to build it... I wish I could avoid this problem ASAP because there are so many noobs having trouble with that.

Yeah I assume when something gets flagged they probably added a quick way to auto detect it and used that as a quick reference. Hopefully the signing can solve that issue.

**Comment by Int-1** [comment]
the offline.exe gave me microleaves adware. Are you aware of this?

**Comment by hjlinde** [comment]
@ferib any luck yet in getting the certificate?

**Comment by ferib** [comment]
@hjlinde cert still pending for verification :/

**Comment by d0t3x** [comment]
I could add you a free certificate since the source code is available here

**Comment by ferib** [comment]
> I could add you a free certificate since the source code is available here, you dont need to spend money on such things since its a free and opensorce indie project btw
> 
> * E: Also I guess that a few people reported the file as "unserious" or blizz did it themselfes thats why it showsup as badfile when downloading the exe, all chromium browsers are able to still download such files its just a headache way to get to allow it

Hey, that would be awesome! could you DM me on Discord? Ferib#6646

**Comment by vonsis** [comment]
https://www.virustotal.com/gui/file/eac6d2113aae460b93bb432a9cf46b226b18dbf64c54f96d13ad3f6cec69e131/detection
Many anti-virus software think it has problems.

**Comment by ferib** [comment]
I am afraid that code signing is signing a deal with the devil, the costs are high and it makes me (as an individual person) vulnerable. I do not want to be put responsible for the actions of others, lets all get used to the malware detection alerts and trust 'Ferib' _(or don't trust him and build from source)_ while we whitelist the tool. In the next releases, I will add a hash to the file so those who are paranoid _(or claim my exe is malicious)_ can check the hash and take my word for it.
