### ISSUE TITLE
Goes back to character screen

### ISSUE THREAD

**Issue by SteamPoweredCat** [ferib/D2R-Offline#35]
when y try to host game it starts loading and then goes back to character selection screen.

**Comment by mfrklic** [comment]
Did you click on TCP/IP or "PLAY"? By default you cannot click "PLAY" to start an existing character but you can use TCP/IP and click HOST to start playing.

The latest version of the beta source has an option to run that unlocks hell mode for your saves (-FixLocalSave flag) which will allow you to use the "PLAY" option again but I do not think it has been compiled for a release yet.

If you are not able to compile the latest beta branch yourself you can grab the following tool in the mean time to manually run against your character save file:
https://github.com/Krydar/D2RSaveFix/releases

**Comment by acidcrash2005** [comment]
Same error! When I create first time person, the game start successfully. But if you back to the start menu,  it starts loading and then goes back to character selection screen. Only TCP/IP start normal like host!

**Comment by mfrklic** [comment]
Sounds like it is still related to this issue #7 

Did you try this tool on your save?
https://github.com/Krydar/D2RSaveFix/releases

**Comment by acidcrash2005** [comment]
Thanks!!!!! Yes it is help!! And now have hell mode!!! Super!!!
