### ISSUE TITLE
D2R-Offline DL Issue

### ISSUE THREAD

**Issue by Mavado78** [ferib/D2R-Offline#46]
For some reason when I try to dl the file it gives me this error : C:\Users\woods\AppData\Local\Temp\IdFIpfxi.zip.part could not be saved, because the source file could not be read.

Any way to fix this issue? Thank you in advance!

**Comment by ferib** [comment]
This is caused by anti-virus and is explained in #33, you may want to whitelist that file in your anti-virus to prevent deletion/block on file.

**Comment by Mavado78** [comment]
Yep, I finally figured it out. I had a derp moment :)
