### ISSUE TITLE
Has anyone got controller support working?

### ISSUE THREAD

**Issue by alextreppass** [ferib/D2R-Offline#47]
I saw a couple of people on Reddit ask the same question. Have tried a few non-MS controllers and they don’t seem to be recognised by the game. Thanks!

**Comment by Crazyloon** [comment]
It should work with an xbox controller

**Comment by mfrklic** [comment]
Yep I just tested it with an XBOX controller and it works! Just woke up the controller mid game and the interface changed to support it. Then went back to my mouse and it switched back. 

I might have to try a couch play through just for the heck of it but I'll primarily play mouse/keyboard.

**Comment by arthurEspooner** [comment]
you could also launch through steam and set a custom steam controller config. if they are recognizing xbox pads, you should be able to set it to 'generic gamepad' template and it will work.

**Comment by Todberg** [comment]
@arthurEspooner Can confirm that this works with the PS5 controller.

**Comment by arthurEspooner** [comment]
@Todberg thanks, i hadn't actually tried yet but i also have a ds5, so good to know. touch pad potions and other stuff could possibly be awesome.

**Comment by arthurEspooner** [comment]
@ferib this can probably be closed.

**Comment by alextreppass** [comment]
@arthurEspooner @Todberg how did you go about doing this through steam? I’ve tried registering it as a non-steam game, and launching through big picture mode, but no luck. PS5 controller wired. Cheers

**Comment by mtodberg** [comment]
@alextreppass Make sure that your PS5 controller is turned on when connected through wire (it needs to have lights turned on afaik). Then add the offline exe to your steam library and go to big picture mode, tick the playstation controller under the controller settings and boot up the game while still in big picture mode using your controller. The controller works in the menu and in-game, but not to skip cutscenes. And also it can take a few seconds before the game registers it.

**Comment by alextreppass** [comment]
Thanks!
