### ISSUE TITLE
Anyone know a fix for overlapping Maps?

### ISSUE THREAD

**Issue by Diablo91020** [ferib/D2R-Offline#49]
When i host a new game on TCP/IP previous versions of the minimap keep overlapping on top of each other, is there a way to reset these maps or fix this issue?
![image](https://user-images.githubusercontent.com/82679857/115137522-82708b00-9fdb-11eb-8fec-2c3c7705ac0e.png)

**Comment by arthurEspooner** [comment]
see #32 

also, you can use https://github.com/Krydar/D2RSaveFix to fix the load into game issue, so you won't have to use tcp/ip which might prevent the map issue from happening. i haven't played tcp/ip, and my map works as single player should.

**Comment by Diablo91020** [comment]
after using the D2RSaveFix, can you still play on TCP/IP?

**Comment by mfrklic** [comment]
> after using the D2RSaveFix, can you still play on TCP/IP?

Yes. And you can delete character.map files in your save game path to resolve the overlaying map issue.

**Comment by Diablo91020** [comment]
Awesome, thank you so much!
