### ISSUE TITLE
Character Load

### ISSUE THREAD

**Issue by evenkuruga** [ferib/D2R-Offline#53]
I'm using the latest release but it won't load my save. I can see my character but if I load my save it just keep going back to the character select. Is that normal?

**Comment by SpudMillions** [comment]
You need to do tcp/ip games

**Comment by evenkuruga** [comment]
Thanks

**Comment by mfrklic** [comment]
> You need to do tcp/ip games

If you want to play local game for shared stash access you can use the following tool on your character save:
https://github.com/Krydar/D2RSaveFix/releases
