### ISSUE TITLE
TCP/IP Greyed out

### ISSUE THREAD

**Issue by cravie** [ferib/D2R-Offline#6]
Currently unable to resume game on a character as the tcp/ip option is greyed out. Windows 10, running as admin. Are there any additional steps to be able to resume the game? people suggest to restart pc and the option will enable, but haven't been successful

**Comment by froggz19** [comment]
For some reason, renaming the exe before launching the game seems 'fix' that... weird.

Rename Game.exe to Game_whateveryouwant.exe and run it using this batch.

@echo off
set gameExe=Game_%random%
ren Game_*.exe %gameExe%.exe
D2ROffline.exe %gameExe%.exe

**Comment by ferib** [comment]
Thanks for reporting, it has come to my attention that the timing of the tool is not correctly synced with the game.
I will work on a fix and hope to get the loader synced with the game in one way or another so that the tool can patch BEFORE any critical game code is executed _(and right after all the critical code is loaded into memory)._

The key is to hit the sweet spot in timing, please try tweaking the value in `program.cs`, Line 43, `Thread.Sleep(1100);` modify the number ``1100`` to reduce delay before patching.

**Comment by cravie** [comment]
@ferib thanks, seems like 500 on sleep resolves the problem on my system. Also can confirm @froggz19 fix of renaming the file before running D2ROffline.exe works. Feel free to close this whenever. Cheers

**Comment by Krydar** [comment]
The other solution would be to patch the Game.exe itself.
Open Game.exe with a hex editor, head to `01A4A980` and patch the "betaEnabled" string with NOPS (90 in hexcode).

**Comment by ferib** [comment]
> The other solution would be to patch the Game.exe itself.

That should work, just make sure to backup your original .exe or you will get crash when you no longer uses the tool.

**Comment by sub108** [comment]
How do I run the game from the .BAT file because I made the .bat file and placed it in the file where the game exe is and I also renamed the game exe to the 'whateveryouwant.exe' but the TCP/IP still is greyed out. please I need help.

**Comment by ferib** [comment]
@sub108 , try this:
> may try to download from release? https://github.com/ferib/D2R-Offline/releases/download/v1.0.1/D2ROffline_v1.0.1.zip

Download those files, unzip them in your Diablo II Resurrected folder and then drag the game.exe on top of the D2ROffline.exe

**Comment by sub108** [comment]
> @sub108 , try this:
> 
> > may try to download from release? https://github.com/ferib/D2R-Offline/releases/download/v1.0.1/D2ROffline_v1.0.1.zip
> 
> Download those files, unzip them in your Diablo II Resurrected folder and then drag the game.exe on top of the D2ROffline.exe

it works now but when i exit and go back on it goes grey again

**Comment by ferib** [comment]
Timing has been improved in `v2.0.2-beta` and should fix invalid patching, which caused this issue.

**Comment by froggz19** [comment]
> How do I run the game from the .BAT file because I made the .bat file and placed it in the file where the game exe is and I also renamed the game exe to the 'whateveryouwant.exe' but the TCP/IP still is greyed out. please I need help.

My post is not a fix, it's just a workaround and you did it wrong... I said, rename **Game.exe** to **Game_whateveryouwant.exe** where **whateveryouwant** part of the file name can be whatever you want, eg. **Game_blabla.exe**. Anyway, this is no longer needed, ferib updated his patcher.

**Comment by CDune23** [comment]
Use Krydar's savegame fixer, import your saves one by one with D2 closed and patch them, no TCP/IP required anymore, single player works. Finally shared stash!

https://github.com/Krydar/D2RSaveFix/releases/tag/v1.0.0

**Comment by sub108** [comment]
> Use Krydar's savegame fixer, import your saves one by one with D2 closed and patch them, no TCP/IP required anymore, single player works. Finally shared stash!
> 
> https://github.com/Krydar/D2RSaveFix/releases/tag/v1.0.0

How do I use this is there a guide?

**Comment by Krydar** [comment]
> > Use Krydar's savegame fixer, import your saves one by one with D2 closed and patch them, no TCP/IP required anymore, single player works. Finally shared stash!
> > https://github.com/Krydar/D2RSaveFix/releases/tag/v1.0.0
> 
> How do I use this is there a guide?

https://github.com/Krydar/D2RSaveFix

There's a readme :P

**Comment by ferib** [comment]
The timing of the patcher has greatly improved and should fix the issues, if that's not the case please re-open.
