### ISSUE TITLE
2.0.5 Crashing after ~5 mins of gameplay

### ISSUE THREAD

**Issue by cyberpunk1294** [ferib/D2R-Offline#60]
After playing ~5-7min. game crashes with v2.0.5, Tryied with new saves, didn't help. Tryied rollback to v2.0.4, everything is fine, even game load with patched saves on v2.0.4

**Comment by a358923958** [comment]
After playing ~5-7min. game crashes with v2.0.5, Tryied with new saves, didn't help.

**Comment by fuba82** [comment]
yep same here, but 2.0.4 works fine!

**Comment by ferib** [comment]
Thanks for the reports, I'm afraid that https://github.com/ferib/D2R-Offline/blob/master/src/Program.cs#L73, `Program.cs:73` is missing the line `Thread.Sleep(25);`. So if you build `v2.0.5` from source, add that line (or pull latest).

**Comment by fuba82** [comment]
> Thanks for the reports, I'm afraid that https://github.com/ferib/D2R-Offline/blob/master/src/Program.cs#L73, `Program.cs:73` is missing the line `Thread.Sleep(25);`. So if you build `v2.0.5` from source, add that line (or pull latest).

thanks!
