### ISSUE TITLE
Ladder Runeword patch is too early/doesn't work

### ISSUE THREAD

**Issue by csuhta** [ferib/D2R-Offline#62]
The ladder runeword patch doesn't work currently. However, setting `1EE3200` to `1` is the correct strategy. It just needs to happen after a game has loaded, I think. It works when you perform the change with CheatEngine, but not with this patch currently since it only patches the client during startup.

**Comment by ferib** [comment]
This patcher was not made to patch dynamic data in the `.data` section, just continue to use Cheat Engine or get a patch that patches the check in the ``.text`` section to have it work properly.

**Comment by csuhta** [comment]
@ferib Right, I was filing this issue because the listed patch in the Readme won't actually work, it has to be done after a game loads
