### ISSUE TITLE
[CRASH] constant crashes with 2.0.5

### ISSUE THREAD

**Issue by drnick88101** [ferib/D2R-Offline#64]
**Describe the crash**
Ever since I downloaded 2.0.5 the game started crashing alot. I went back to 2.0.4 and the crashes are gone

**Which version did you use?**
2.0.5

**Which patches.txt did you use?**
I used the same patches.txt that came with the zip

**Comment by ferib** [comment]
The latest commit has fixed this, will push a release in a minute!

**Comment by drnick88101** [comment]
sorry for not noticing. i only check the open issues, didnt think to check the closed ones. thanks for fixing it!
