### ISSUE TITLE
[CRASH] constant crashes with 2.0.5 hotifx

### ISSUE THREAD

**Issue by drnick88101** [ferib/D2R-Offline#66]
**Describe the crash**
 I just downloaded the hotfix and it is still crashing and it is still crashing alot. Someone in this discord server im in mentioned that it might just be the classes that were not part of the alpha test that might be crashing. i was playing assassin and it crashed for me.

**Which version did you use?**
2.0.5 hotfix

**Which patches.txt did you use?**
I used the same patches.txt that came with the zip

**Comment by ferib** [comment]
I am currently investigating these issues, can you try version `2.0.4` and see if everything works fine?

**Comment by drnick88101** [comment]
yeah, version 2.0.4 is still ok. and never mind about it only effect classes not part of alpha. someone in discord said it crashed on their barbarian

**Comment by mfrklic** [comment]
Yeah I was having problems today with 2.0.5 as well for some reason today with unexpected crashes. Went back to 2.0.4 and seems good and stable again.

**Comment by mpietro87** [comment]
Same problem with 2.0.5

**Comment by diaderik** [comment]
I have been playing on version 2.0.5 for more than 5 hours. Сompiled exe-file it myself from source code.

**Comment by evilight** [comment]
for me, the only stable version is still the old v1.0.1
the game will crash after maybe 3-4 minutes with 2.0.4 beta or 2.0.5

**Comment by Qerdo97** [comment]
I can confirm that, on 2.0.5 is crushing after few second of playing as a barbarian char. On 2.0.4 working like a charm

**Comment by ammadeusy** [comment]
2.0.5 crashes randomly, any char.

**Comment by Frikico** [comment]
Yup game opens and seem to work perfectly then I play like 2 mins and it crash. Playing on 2.0.5 paladin and druid.

**Comment by ferib** [comment]
> Yup game opens and seem to work perfectly then I play like 2 mins and it crash. Playing on 2.0.5 paladin and druid.

> 2.0.5 crashes randomly, any char.

> the game will crash after maybe 3-4 minutes with 2.0.4 beta or 2.0.5

> Yeah I was having problems today with 2.0.5 as well for some reason today with unexpected crashes. Went back to 2.0.4 and seems good and stable again.

Time to get v2.0.6, if for some reason you still crash, use the  `-Delay` argument like this: `./D2ROffline.exe -Delay 100` to extend the patching delay (default is 25ms).

**Comment by Lomwen** [comment]
the argument -Delay doesn't work for me, what am I doing wrong?
![image](https://user-images.githubusercontent.com/82873338/115370103-063b9a80-a1c9-11eb-9c45-00cca4c710a9.png)

**Comment by drnick88101** [comment]
> the argument -Delay doesn't work for me, what am I doing wrong?
> ![image](https://user-images.githubusercontent.com/82873338/115370103-063b9a80-a1c9-11eb-9c45-00cca4c710a9.png)

Easiest way to do this would be to create a d2roffline.exe shortcut on your desktop. Then edit the shortcut to run this: C:\D2R\D2ROffline.exe C:\D2R\GAME.EXE -Delay 100
i guess you could also type that into the command prompt like you were trying to do as well

**Comment by ferib** [comment]
> the argument -Delay doesn't work for me, what am I doing wrong?

Yeah you forgot the game arg as @drnick88101 pointed out ``./D2ROffline.exe Game.exe -Delay 69``. For me the easiest way is the command prompt, but yeah using a shortcut like this should also do the trick:
![image](https://user-images.githubusercontent.com/22753171/115415499-4154c280-a1f7-11eb-9c46-a94ea912f59d.png)

**Comment by drnick88101** [comment]
2.0.6 seems to have fixed it. Ive been playing for about 2 hours with no crash and I didnt even have to use -delay

**Comment by Lomwen** [comment]
> > the argument -Delay doesn't work for me, what am I doing wrong?
> 
> Yeah you forgot the game arg as @drnick88101 pointed out `./D2ROffline.exe Game.exe -Delay 69`. For me the easiest way is the command prompt, but yeah using a shortcut like this should also do the trick:
> ![image](https://user-images.githubusercontent.com/22753171/115415499-4154c280-a1f7-11eb-9c46-a94ea912f59d.png)

Thx! Missing game.exe was the problem.

Now I have one more issue with commands in patch.txt
0x1EE3200:90: ~ allowLadderRunewords
0x1EE3201:90: ~ displayItemLevel

Sometimes, it works, however very rarely. I have no idea what it depends on.

I was trying different timing with no results.

**Comment by ferib** [comment]
> Now I have one more issue with commands in patch.txt
0x1EE3200:90: ~ allowLadderRunewords
0x1EE3201:90: ~ displayItemLevel

> Sometimes, it works, however very rarely. I have no idea what it depends on.

> I was trying different timing with no results.

https://github.com/ferib/D2R-Offline/blob/master/FAQ.md#how-do-i-enable-ladder-runewords
