### ISSUE TITLE
Can't load legacy character after -FixLocalSave

### ISSUE THREAD

**Issue by penut85420** [ferib/D2R-Offline#67]
After `-FixLocalSave` it show that save file had been patched, but after entering the game it said "Unable to enter game. Bad character quest data."

Any idea?

**Comment by mfrklic** [comment]
Legacy character support is very limited -- similar issue reported here:
#63

**Comment by dschu012** [comment]
I think saves legacy saves in a3 or higher have issues. Maybe write [0x128, 0x0, 0x0] at 0xA8 to force them to be in A1 normal?
