### ISSUE TITLE
cannot load into save

### ISSUE THREAD

**Issue by danelsck** [ferib/D2R-Offline#7]
i created a character but after save and exit and i try to load the character again it attempts to load but then sends me back to character selection screen. am i doing something wrong?

**Comment by ferib** [comment]
You may want to host a `tcp/ip` to be able to play that saved character again.

**Comment by FunkyMunky1** [comment]
FYI: putting items in shared stash in TCP/IP game is a great way to lose them :)

**Comment by Krydar** [comment]
You have to edit your .d2s file with a hex editor or hero editor to make the character clear normal, otherwise it won't load.

**Comment by danelsck** [comment]
> 
> 
> You may want to host a `tcp/ip` to be able to play that saved character again.

thank you! :) great tool

**Comment by FunkyMunky1** [comment]
>make the character clear normal

any idea what byte values I need to change?

**Comment by Khiu** [comment]
Change 0x25 to 08 and fix the checksum. For checksum calculation see: https://github.com/ternence-li/Diablo2HeroEditor/blob/18b7633c437c8da6a1f8b5797b126458489e8bc5/Diablo2FileFormat/Checksum.cs

**Comment by 77920** [comment]
> Change 0x25 to 08 and fix the checksum. For checksum calculation see: https://github.com/ternence-li/Diablo2HeroEditor/blob/18b7633c437c8da6a1f8b5797b126458489e8bc5/Diablo2FileFormat/Checksum.cs

What does this accomplish?

**Comment by Khiu** [comment]
What funkymunky was asking about, the bytes and values to change so your char has finished normal. This enables you to load saved chars.

**Comment by dotnetprog** [comment]
> You have to edit your .d2s file with a hex editor or hero editor to make the character clear normal, otherwise it won't load, and force recheck the CRC for the d2s file as well.

I tried hero editor and the file wont load properly in hero editor 
have a turorial on this? Regarding the 0x25 value to 0x08, in my file it seems no byte with 0x25 in it

can you give some details?

**Comment by mfrklic** [comment]
I see the 0x25 value to hex to 0x08 but no idea how to force the update checksum via hero editor when the d2s file is not compatible. How is everyone else doing this?

The TCP/IP option seems to work at least but since I am only playing solo would be nice to have access to shared stash.

**Comment by nt153133** [comment]
I made a small c# program to set the byte and save the new checksum. The checksum calc code is a direct copy and paste from the hero editor linked. Should make it easier to fix your saves https://github.com/nt153133/D2RSaveFix

**Comment by mfrklic** [comment]
> I made a small c# program to set the byte and save the new checksum. The checksum calc code is a direct copy and paste from the hero editor linked. Should make it easier to fix your saves https://github.com/nt153133/D2RSaveFix

Thanks for this! Works perfectly!

**Comment by fearhq** [comment]
Where are the saves located?

**Comment by Gati119** [comment]
> I made a small c# program to set the byte and save the new checksum. The checksum calc code is a direct copy and paste from the hero editor linked. Should make it easier to fix your saves https://github.com/nt153133/D2RSaveFix

I don't understand how this Hero editor work. I download the Diablo 2 Hero editor, but there is no exe file in there... How you start the program?....

**Comment by xolived** [comment]
> 
> 
> Where are the saves located?

C:\Users\youruser\Saved Games\Diablo II Resurrected Tech Alpha

**Comment by dotnetprog** [comment]
> > I made a small c# program to set the byte and save the new checksum. The checksum calc code is a direct copy and paste from the hero editor linked. Should make it easier to fix your saves https://github.com/nt153133/D2RSaveFix
> 
> I don't understand how this Hero editor work. I download the Diablo 2 Hero editor, but there is no exe file in there... How you start the program?....

Its very simple 

1# download visual studio 2019 community or professional(google it)
#2 install .net framework 8 (google it)
#3 open the downloaded project with visual studio 2019
#4 click start 
#5 voilà

**Comment by Blindmikey** [comment]
Changed 0x25 to the value of 0x08 with HxD and when I attempt to play the character, I get "Game is Full" and kicks me back out to char selection screen. 

https://imgur.com/a/y85UayL

**Comment by Krydar** [comment]
> Changed 0x25 to the value of 0x08 with HxD and when I attempt to play the character, I get "Game is Full" and kicks me back out to char selection screen.
> 
> https://imgur.com/a/y85UayL

Please read the comments before commenting. This fixes your problem.
https://github.com/nt153133/D2RSaveFix

**Comment by Blindmikey** [comment]
I did read the comments, and attempted to follow but came up against a registration requirement (from visual studio) when running D2RSaveFix.sln from https://github.com/nt153133/D2RSaveFix and new I already had a Hex editor. Apologies, this isn't my world so I'm wondering half blind.

**Comment by Krydar** [comment]
It's gonna take a lot more than a hex edit to fix the issue, you need to do a checksum recalculation.
Try this, I forked and compiled. Should work.
https://github.com/Krydar/D2RSaveFix/releases/tag/v1.0.0

**Comment by Gati119** [comment]
> > > I made a small c# program to set the byte and save the new checksum. The checksum calc code is a direct copy and paste from the hero editor linked. Should make it easier to fix your saves https://github.com/nt153133/D2RSaveFix
> > 
> > 
> > I don't understand how this Hero editor work. I download the Diablo 2 Hero editor, but there is no exe file in there... How you start the program?....
> 
> Its very simple
> 
> 1# download visual studio 2019 community or professional(google it)
> #2 install .net framework 8 (google it)
> #3 open the downloaded project with visual studio 2019
> #4 click start
> #5 voilà

Thank you. It's worked!

**Comment by pabs416** [comment]
So question, I changed 0x25 to the value of 0x18 in order to gain access to hell but I'm pretty sure I'm messing up the checksum and not sure how to fix it. It does let me select hell and loads then gives me the game is full error.

Anyone able to help?
