### ISSUE TITLE
2.0.3 - 2.0.5. LAN Multiplayer constant packet loss

### ISSUE THREAD

**Issue by deadjack133** [ferib/D2R-Offline#74]
Looks like there is issue with tcp/ip multiplayer right now, because even if i host game, there is constant issues when player character can't attack mobs in certain areas. It's looks like player can't hit creature because of constant missing. Does anyone else experience similar problem?

**Comment by LazG7** [comment]
Same but I'll admit it's 100% old netcode from OG D2 as this is the same behavior you can/would see on bnet as well. I hope Vicarious is addressing this.

**Comment by deadjack133** [comment]
Thank you for clarification!
