### ISSUE TITLE
Map doesn't reset

### ISSUE THREAD

**Issue by lh82ps** [ferib/D2R-Offline#75]
in each game, the map of the previous game remains. therefore, it is very difficult to orientate yourself with the minimap. Is there a way to delete the map of the previous game?

I have tried it with:

0x1EE31FC:90: ~ AlwaysRegenMapInSP

but it does not work.

**Comment by mfrklic** [comment]
Others that have had this problem have fixed it by deleting their character.map file.

**Comment by csuhta** [comment]
This isn't related to the patcher. It's a bug in the alpha. Delete the .ma files in your save directory to clear the map drawings.

**Comment by ferib** [comment]
https://github.com/ferib/D2R-Offline/blob/master/FAQ.md#why-is-my-map-overlappingnot-displaying-properly
