### ISSUE TITLE
Add FaQ?

### ISSUE THREAD

**Issue by ferib** [ferib/D2R-Offline#77]
It seems like a lot of these issues are duplicates of another.

Things like "cannot access stash on tcp/ip", "buttons not unlock", "cannot join my friends IP", "game crash after X", etc..

Would be nice to have a collection of these commonly asked questions, together with an answer so people can be pointed in the right directions before they open up an issue!

**Comment by DartPower** [comment]
First mentioned problem as i remember, which breaks game it's "Read only" on files and/or folders.

**Comment by creambyemute** [comment]
Second one is the BNetInstaller. Depending on the console you have to use
`Bnetinstaller.exe <...args>` (idk who uses this)
`./Bnetinstaller.exe <...args>` (unix like shells/clis)
`.\Bnetinstaller.exe <..args>` (powershell?)

**Comment by penut85420** [comment]
> `Bnetinstaller.exe <...args>` (idk who uses this)

@creambyemute The windows command prompt uses this

**Comment by ferib** [comment]
Alright here we go: https://github.com/ferib/D2R-Offline/blob/master/FAQ.md
PR's related to documentation can go directly to the `master` branch, I think it's best to have a well-updated readme to prevent duplicated issues.

**Comment by creambyemute** [comment]
@mfrklic Sorry I'm really not a windows guy. Windows is so weird with the backslash, carriage return, weird and slow af file system.

Whenever I use a console on windows it's a unix like one like git bash ;)

**Comment by ferib** [comment]
FaQ has been added, thanks y'all!
