### ISSUE TITLE
Can you help me install?

### ISSUE THREAD

**Issue by TomBigelow1986** [ferib/D2R-Offline#8]
Thanks for making this. I'm looking for help to get it working. This is what I did so far:

I downloaded visual studio 2019
I cloned the repo
I opened the folder in visual studio code (note I chose open folder not project)
 I found a way to add .net core 3.1 inside visual studio
I ran dotnet build in the terminal and it said build successful but not sure what the output of this command is. Is there a new file created from this?

I dont understand the other 2 instructions and need some hand holding:
1)Move to output cd bin/Debug/dotnetcore3.1/

2) Finally, launch the executable using path to game.exe as argument ./D2ROffline.exe C:/D2R/Game.exe

*there is also another section that I'm not sure I need that says game files. I downloaded the bnet installer but not sure what to do with arguments.

**Comment by FunkyMunky1** [comment]
Download that bnetinstaller executable

Open terminal and go to where you downloaded that executable and type the following:
```BNetInstaller.exe --prod osib --lang enus --dir "C:\D2R"```

Then go to the terminal where you ran the build command, type the following:

```cd bin/Debug/dotnetcore3.1/```

Then to start the game type
```D2ROffline.exe C:/D2R/Game.exe```

**Comment by TomBigelow1986** [comment]
> Download that bnetinstaller executable
> 
> Open terminal and go to where you downloaded that executable and type the following:
> `BNetInstaller.exe --prod osib --lang enus --dir "C:\D2R"`
> 
> Then go to the terminal where you ran the build command, type the following:
> 
> `cd bin/Debug/dotnetcore3.1/`
> 
> Then to start the game type
> `D2ROffline.exe C:/D2R/Game.exe`

Thanks so much for your reply. I'm running the bnetinstaller right now. Just 1 thing--you said:
`cd bin/Debug/dotnetcore3.1/`

However in my bin/Debug folder there is only a folder called netcoreapp3.1.

**Comment by FunkyMunky1** [comment]
> there is only a folder called netcoreapp3.1.

then do that one :)

**Comment by TomBigelow1986** [comment]
It's working thanks!
