### ISSUE TITLE
Patches loading fails

### ISSUE THREAD

**Issue by VcAsHew** [ferib/D2R-Offline#82]
The gameplay features in patches.txt (e. g. ladder runewords) are not available after I added the rules into the file.

I also tried v2.0.5 and it didn't work either.

**Comment by VcAsHew** [comment]
Have to reopen this issue. Already tried the solutions in other posts but none of them works.

**Comment by ferib** [comment]
The misleading patches for the `.data` sections have been removed from the readme.
