### ISSUE TITLE
[CRASH] Crash sponteneous, Successful save and loading game, Ask 4 Ferib

### ISSUE THREAD

**Issue by roomkiller** [ferib/D2R-Offline#85]
Hi, I noticed that the game was closing by itself for no reason, a few seconds after joining the game, that's the first bug, the second is that I had to create a shortcut to be able to him put the -FixLocalSave command instead of using your original patch, however I managed to use my character save for the first time Bravo! have is on the right track .. if you can correct the spontaneous closing that would be really appreciated, as well as the -FixLocalSave if you could explain it better ... me i created a shortcut for your D2ROffline 2.0.5 i I entered the -fixlocalsave command in the priority I applied the command and then I drop the game.exe executable on the.exe shortcut that told me to have created my backup, then I took the game.exe and I drop them on the original D2Roffline .. I use a translator I hope it will be clear as well thank you boys

i resolved sponteneous crash, with put back 2.0.4 patch

So you take the patch 2.0.5 you copy it in the original D2R folder, Then you create a shortcut of the executable D2ROffline2.0.5.exe, right click on it you open the properties, in the first field of the name of target: E: \ D2R \ D2ROffline.exe -FixLocalSave then you click on apply. all this closes, you select the executable Game.exe you put it on D2ROffline. A dos command window opens, the patch confirms that the creation of the backup files has been created, you can then download D2ROffline2.0.4.exe that you drop into the original D2R folder and replace 2.0.5 to correct the spontaneous crash short for now it looks like this and it works for me

Now I play stably and can load my character without diffulculty, I have saved my level 4 character and quit the game to restart it all still working .. so if that can help someone so much the better

**Comment by ferib** [comment]
For the command-line options, all you have to do is open a CDM, Powershell, Gitbash or anything and type `./D2ROffline.exe -FixLocalSave` to get it going.

> i resolved sponteneous crash, with put back 2.0.4 patch
v2.0.6 should fix the crashing, you can also make use of `-Delay` to delay patching, which increases the success rate of the patching. The usage: `./D2ROffline.exe -Delay 100` to use 100ms (default 25ms).

**Comment by roomkiller** [comment]
Thx alot !!

**Comment by kruc3f1x** [comment]
i'm getting stuck at the loading screen whenever i use town portal inside of a building/cave, is there anything to do  about this issue? It's getting really frustrating :/

**Comment by shollak** [comment]
> For the command-line options, all you have to do is open a CDM, Powershell, Gitbash or anything and type `./D2ROffline.exe -FixLocalSave` to get it going.
> 
> > i resolved sponteneous crash, with put back 2.0.4 patch
> 
> v2.0.6 should fix the crashing, you can also make use of `-Delay` to delay patching, which increases the success rate of the patching. The usage: `./D2ROffline.exe -Delay 100` to use 100ms (default 25ms).

I have random crashing too and saw the timer and your comment in the code but I couldn't figure out how to compile.

My friend doesn't crash at all.
Gonna try this, thanks!

I also crash when loading completes trying to join ferib.dev, gonna try opening ports.

**Comment by ferib** [comment]
> > For the command-line options, all you have to do is open a CDM, Powershell, Gitbash or anything and type `./D2ROffline.exe -FixLocalSave` to get it going.
> > > i resolved sponteneous crash, with put back 2.0.4 patch
> > 
> > 
> > v2.0.6 should fix the crashing, you can also make use of `-Delay` to delay patching, which increases the success rate of the patching. The usage: `./D2ROffline.exe -Delay 100` to use 100ms (default 25ms).
> 
> I have random crashing too and saw the timer and your comment in the code but I couldn't figure out how to compile.
> 
> My friend doesn't crash at all.
> Gonna try this, thanks!
> 
> I also crash when loading completes trying to join ferib.dev, gonna try opening ports.

No need to compile, here is latest release: https://github.com/ferib/D2R-Offline/releases/tag/v2.0.6

**Comment by Limit-byte** [comment]
Love your work ferib! Thanks so much! Im a noob with this stuff but ive got it running been playing in tcp ip, very easy setup but cant seem to get the local save patch working after initial session. tcp ip is fine for now but seems laggy compared to local, hits dont register etc. when i load local i just get the loading screen hang for a second then back to character select. So to be clear the steps would be: open D2ROffline.exe open Powershell and input ./D2ROffline.exe -FixLocalSave ? because this just gives error: "" is not recognized blah blah... am i missing some thing?

**Comment by fuba82** [comment]
> > > For the command-line options, all you have to do is open a CDM, Powershell, Gitbash or anything and type `./D2ROffline.exe -FixLocalSave` to get it going.
> > > > i resolved sponteneous crash, with put back 2.0.4 patch
> > > 
> > > 
> > > v2.0.6 should fix the crashing, you can also make use of `-Delay` to delay patching, which increases the success rate of the patching. The usage: `./D2ROffline.exe -Delay 100` to use 100ms (default 25ms).
> > 
> > 
> > I have random crashing too and saw the timer and your comment in the code but I couldn't figure out how to compile.
> > My friend doesn't crash at all.
> > Gonna try this, thanks!
> > I also crash when loading completes trying to join ferib.dev, gonna try opening ports.
> 
> No need to compile, here is latest release: https://github.com/ferib/D2R-Offline/releases/tag/v2.0.6

Crashes are just because the the `-Delay` Argument is not working right now.
Please look at my _https://github.com/ferib/D2R-Offline/issues/91#issuecomment-823862918_ here.

**Comment by ferib** [comment]
@fuba82 thanks for pointing that out, I have released `v2.0.7` with the fix for the `-Delay` arg.
