### ISSUE TITLE
Items in shared stash disappeared (v2.0.6)

### ISSUE THREAD

**Issue by ramonchen** [ferib/D2R-Offline#89]
All items in shared stash will disappear after restarting game.  Tested several times with v2.0.6 release, 100% reproduced.
Is this a d2r alpha bug or an offline patch bug ?

**Comment by csuhta** [comment]
Shared stash doesn’t work in TCP/IP games. It’s an alpha bug.

**Comment by ramonchen** [comment]
> Shared stash doesn’t work in TCP/IP games. It’s an alpha bug.
@csuhta Thanks for your reply.
