### ISSUE TITLE
[Question] Cheat Engine Table????

### ISSUE THREAD

**Issue by CanadianJeff** [ferib/D2R-Offline#90]
if all this patch is doing is modifying memory could a simple cheat engine script do the same thing?

**Comment by ferib** [comment]
No and no, my patcher is not only patching code at startup, it is also bypassing integrity check so your game won't crash when patches are done.

However, you can use Cheat Engine for patching stuff inside the `.rdata` section, but thats a more advanced thing that is out of scope for this project.

**Comment by CanadianJeff** [comment]
shucks I was hoping for an easy solution with cheat engine without needing to compile anything
