### ISSUE TITLE
2.0.7 maximum patch sized reached!

### ISSUE THREAD

**Issue by Exodusek** [ferib/D2R-Offline#93]
> ```
> [14:43:33.58683]: Delay has been set to: 50ms
> [14:43:33.58683]: Launching game...
> [14:43:33.61688]: Process started...
> [14:43:33.61688]: Opening process...
> [14:43:33.62656]: Waiting for data at 0x7FF79ABC8858...
> [14:43:33.95664]: Suspending process...
> [14:43:33.95664]: Process suspended
> [14:43:33.95664]: Remapping process..
> [14:43:34.01230]: Patching 0x7FF79A7D3201
> [14:43:34.01230]: Patching 0x7FF798A346C8
> [14:43:34.01230]: Patching 0x7FF79A7D320E
> [14:43:34.01230]: Patching 0x7FF79A7D31FC
> [14:43:34.01230]: Patching 0x7FF79A7D3202
> [14:43:34.01681]: Patching 0x7FF79A7D3204
> [14:43:34.01681]: Patching 0x7FF79963AD68
> [14:43:34.01681]: Patching 0x7FF79963E25F
> [14:43:34.01681]: Patch 0x7FF79959FB9D reject, maximum patch sized reached!
> [14:43:34.01681]: Patch 0x7FF798E87E1C reject, maximum patch sized reached!
> [14:43:34.01681]: Patch 0x7FF79954E81C reject, maximum patch sized reached!
> [14:43:34.01681]: Patch 0x7FF7996515F2 reject, maximum patch sized reached!
> [14:43:34.01681]: Patch 0x7FF798C8FC03 reject, maximum patch sized reached!
> [14:43:34.01681]: Patch 0x7FF798C8FCB6 reject, maximum patch sized reached!
> [14:43:34.01681]: Bypassed CRC at 7FF7989A54D0
> [14:43:34.01681]: Bypassed CRC at 7FF7989A7430
> [14:43:34.02687]: Bypassed CRC at 7FF798A562B1
> [14:43:34.02687]: Bypassed CRC at 7FF798AAD901
> [14:43:34.04680]: Bypassed CRC at 7FF7995058C0
> [14:43:34.04680]: Bypassed CRC at 7FF799505DB0
> [14:43:34.04680]: Bypassed CRC at 7FF799512251
> [14:43:34.04680]: Bypassed CRC at 7FF7995128D0
> [14:43:34.05664]: Bypassed CRC at 7FF799AD8111
> [14:43:34.06647]: Bypassed CRC at 7FF799E0C501
> [14:43:34.06647]: Bypassed CRC at 7FF799E2CFD1
> [14:43:34.06647]: Bypassed CRC at 7FF799E3FC71
> [14:43:34.06647]: Bypassed CRC at 7FF799E57891
> [14:43:34.06647]: Bypassed CRC at 7FF799E5F690
> [14:43:34.06647]: Bypassed CRC at 7FF799E65FC0
> [14:43:34.06647]: Bypassed CRC at 7FF799E823A0
> [14:43:34.06647]: Bypassed CRC at 7FF799E8D9B1
> [14:43:34.06647]: Bypassed CRC at 7FF799E97DD1
> [14:43:34.07667]: Bypassed CRC at 7FF799EB4791
> [14:43:34.07667]: Bypassed CRC at 7FF799EDEA30
> [14:43:34.07667]: Bypassed CRC at 7FF799EE2D31
> [14:43:34.07667]: Bypassed CRC at 7FF799EEFB61
> [14:43:34.07667]: Bypassed CRC at 7FF799F03930
> [14:43:34.07667]: Bypassed CRC at 7FF799F0C8F1
> [14:43:34.07667]: Bypassed CRC at 7FF799F0E981
> [14:43:34.07667]: Bypassed CRC at 7FF799F202E0
> [14:43:34.07667]: Bypassed CRC at 7FF799F242F0
> [14:43:34.07667]: Bypassed CRC at 7FF799F2CAE1
> [14:43:34.07667]: Bypassed CRC at 7FF799F30771
> [14:43:34.07667]: Bypassed CRC at 7FF799F33F81
> [14:43:34.07667]: Bypassed CRC at 7FF799F35D71
> [14:43:34.07667]: Bypassed CRC at 7FF799F4AFF1
> [14:43:34.07667]: Bypassed CRC at 7FF799F50A50
> [14:43:34.08662]: Bypassed CRC at 7FF799F783B1
> [14:43:34.08662]: Bypassed CRC at 7FF799F88961
> [14:43:34.10666]: Resuming process..
> [14:43:34.10666]: Done!
> [14:43:34.10666]: Press any key to exit...
> ```

Is there a possibility of more than just 8 patches?

**Comment by ferib** [comment]
To prevent people from spreading malicious `patches.txt` I decided to set a maximum amount of patches for `128` bytes.
