### ISSUE TITLE
language patch is not loading on version 2.0.7

### ISSUE THREAD

**Issue by Huppsy1337** [ferib/D2R-Offline#96]
the other patches are working fine, am i doing something wrong?

i am using:

0x1446C8:+0x270A4: ~ German *[deDE]*

thanks for your help :-)

**Comment by ferib** [comment]
make use of the delay, try to lower it just enough so the language load while the game is stable enough and not crashes after a couple of minutes. Usage: ``./D2ROffline.exe Game.exe -Delay 20``

**Comment by Huppsy1337** [comment]
thank you! im already using the delay, and it is kind of weird. with delay 20, the game is german and the ladder runewords and ilvl patches dont work. 
with delay 50, the game is english and the other patches work then. 
on delay 49 same ( english and ilvl + ladder runewords working ), 
but on delay 48 game is german again and no other patches are loading.

**Comment by ferib** [comment]
Timing is based on your CPU/device.
https://github.com/ferib/D2R-Offline/blob/master/FAQ.md#how-do-i-enable-ladder-runewords
